version: "3.6"
services: 
    postgres:
        image: postgres
        container_name: postgres-container 
        restart: always
        volumes: 
            - ./postgress/data:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: keycloack
            POSTGRES_PASSWORD: 123456
    keycloack:
        image: jboss/keycloak
        container_name: keycloack-container
        restart: always
        ports: 
            - "8080:8080"
        environment: 
            KEYCLOACK_USER: admin
            KEYCLOACK_PASSWORD: admin
            DB_VENDOR: postgres
            DB_ADDR: postgres-container
            DB_USER: keycloack
            DB_PASSWORD: 123456
        depends_on: 
            - postgres                